== Start of demo

[source]
start with: tmux attach || tmux new

== Environment and jshell

. jenv: `jenv shell 9-ea`
.. jenv not to mess with JDK version between different environments
.. like rvm but for Java
.. recently JDK is also featured package for sdkman.io

. running jshell for the first time
.. /help (/?)
.. `4+4`
.. `$5 + 4`
.. Variable naming
.. Using variables
.. Default imports (`Math.min()`)
.. Tab completion + Shift + Tab smart autocompletions

. commands
.. define interface +
+
[source]
----
interface ConvertToString {
	String apply(Integer i);
}
----
.. inline +
+
[source]
----
jshell> String convertToString(Integer i) {
   ...> return i.toString();
   ...> }
----
.. /edit toString
.. /set editor vim
.. /edit toString
.. /list
.. /vars
.. export EDITOR=/usr/bin/vim
.. /save `tofile`

== Java 9

. Java9 Enhancements
.. `Set.of()` - JAX-RS
... `<Set<Class<?>> getClasses()` +
+
[source]
----
jshell> interface Application {
   ...> Set<Class<?>> getClasses();
   ...> }
----
... `Application a = () -> new HashSet<Class<?>>(Arrays.asList(Math.class, Integer.class));`
... `Application b = () -> Set.of(Math.class, Integer.class);`
.. `List.of()`
.. Streams Enhancements
... `List<Integer> list = Arrays.asList(1, 2, 3, 4, null)`
... Map +
+
[source]
----
$1.stream()
	.map(Optional::ofNullable)
----
... No flatMap of Optional +
+
[source]
----
$1.stream()
  .map(Optional::ofNullable)
  .flatMap(o -> o.map(Stream::of).orElse(Stream.empty()))
  .forEach(System.out::println)
----
... `Optional::stream` +
+
[source]
----
$1.stream()
	.map(Optional::ofNullable)
	.flatMap(Optional::stream)
	.forEach(System.out::println)
----
... `takeWhile` +
+
[source]
----
$8.stream()
	.takeWhile(Objects::nonNull)
	.forEach(System.out::println)
----
... Infinite streams
+
[source]
----
IntStream.iterate(0, i -> 2 * i)
    .takeWhile(i -> i < 42)
    .forEach(System.out::println)
----
... Without `takeWhile` +
+
[source]
----
IntStream
	.iterate(1, i -> i < 42,  i -> i + 1)
	.forEach(System.out::println)
----

. HttpRequest
.. `/reset`
.. http://download.java.net/java/jdk9/docs/api/jdk/incubator/http/HttpRequest.html
.. jshell> /env --add-modules jdk.incubator.httpclient
.. jshell> import jdk.incubator.http.*
.. jshell> import static jdk.incubator.http.HttpRequest.*
.. jshell> import static jdk.incubator.http.HttpResponse.*
// .. jshell> import java.net.http.*
// .. jshell> import static java.net.http.HttpRequest.*
// .. jshell> import static java.net.http.HttpResponse.*
.. Parse JSON from external URI (`https://micro-patterns-profanity.herokuapp.com/checkprofanity?text=This%20is%20shit`)
... Show it in console, curl
.. URL url = new URL("https://micro-patterns-profanity.herokuapp.com/checkprofanity?text=This%20is%20shit");
.. `HttpRequest.Builder` +
+
[source]
----
HttpRequest
	.newBuilder(url.toURI())
	.GET()
	.build()
----
.. `HttpClient.Buidler` +
+
[source]
----
HttpClient
	.newHttpClient()
	.send($6, BodyHandler.asString())
----
.. header in requests +
+
[source]
----
HttpRequest
	.newBuilder(url.toURI())
	.header("Accept", "application/json")
	.GET()
	.build()
----

.. No - there are no specific plans to unify it with JAX-RS
.. It's based on Flow API (`HttpRequest.BodyProcessor` implements `Flow.Producer` while `HttpResponse.BodyProcessor` implements `Flow.Subscriber`
.. Gson path: /home/kubam/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar

== Working with external dependencies

. Starting with external deps
.. `/reset`
.. `/env --class-path /home/kubam/.m2/repository/com/sparkjava/spark-core/2.5/spark-core-2.5.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-api/1.7.24/slf4j-api-1.7.24.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-simple/1.7.24/slf4j-simple-1.7.24.jar:/home/kubam/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/home/kubam/.m2/repository/org/eclipse/jetty/aggregate/jetty-all/9.3.6.v20151106/jetty-all-9.3.6.v20151106-uber.jar:/home/kubam/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar`
.. `System.getProperty("java.class.path")`

. Initialize (`snippers/1_ignite.jsh`)
.. import spark.*
.. Service http = Service.ignite()
.. http.port(8888)
.. http.init()


. Basic endpoint
.. `Route r = (req, resp) -> ""`
.. /edit r
.. `route` +
+
[source]
----
Route r = (req, resp) -> {
	resp.header("Content-type", "application/json");
	return "{'foo': 'bar'}";
}
----
.. `http.get("/json", r)`
.. show in the browser http://localhost:8888/json
.. edit `:s/'/\\"/g` +
+
[source]
----
Route r = (req, resp) -> {
	resp.header("Content-type", "application/json");
	return "{\"foo\": \"bar\"}";
}
----
.. `/save /tmp/json.jsh`
.. exit and load
... doesn't work - so start with `--class-path`
... `/home/kubam/.m2/repository/com/sparkjava/spark-core/2.5/spark-core-2.5.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-api/1.7.24/slf4j-api-1.7.24.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-simple/1.7.24/slf4j-simple-1.7.24.jar:/home/kubam/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/home/kubam/.m2/repository/org/eclipse/jetty/aggregate/jetty-all/9.3.6.v20151106/jetty-all-9.3.6.v20151106-uber.jar:/home/kubam/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar`
... doesn't work - so add `/env` command
... `/env --class-path /home/kubam/.m2/repository/com/sparkjava/spark-core/2.5/spark-core-2.5.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-api/1.7.24/slf4j-api-1.7.24.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-simple/1.7.24/slf4j-simple-1.7.24.jar:/home/kubam/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/home/kubam/.m2/repository/org/eclipse/jetty/aggregate/jetty-all/9.3.6.v20151106/jetty-all-9.3.6.v20151106-uber.jar:/home/kubam/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar`

== GSON

.. import com.google.gson.*
.. `Gson gson = new Gson()`
... add `gson::toJson`
.. `http.get("/foo", (req, resp) -> List.of(1,2,3,4,5), gson::toJson)`

== Application

. Show `snippets/JavaApp.class`
.. `export CP=/home/kubam/.m2/repository/com/sparkjava/spark-core/2.5/spark-core-2.5.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-api/1.7.24/slf4j-api-1.7.24.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-simple/1.7.24/slf4j-simple-1.7.24.jar:/home/kubam/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/home/kubam/.m2/repository/org/eclipse/jetty/aggregate/jetty-all/9.3.6.v20151106/jetty-all-9.3.6.v20151106-uber.jar:/home/kubam/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar`
.. `javac -cp $CP snippets/JavaApp.java`
.. when compiles run it `java -cp .:$CP JavaApp`

== Application - endpoints

. If we can prepare snippets and run them, maybe we can prepare complete application
. Copy `JavaApp.java` to `app.jsh`
.. run it with `jshell --class-path $CP app.jsh`
.. backup: `/open snippets/2_application.jsh`
. show in browser
. add a simple Todo
. show in jshell
. `storage.clear()`
. show in browser

== Run from shell

. Run from bash `jshell snippets/2_application.jsh`
. Copy `snippets/2_application.jsh` to `bash_app.jsh`
. Add `#!/opt/java/jdk-9/bin/jshell`
. `chmod a+x bash_app.jsh`
. Run it as a bash

== Mavenized project

. Maven
.. from jshell `jshell -c target/classes/:$CP`
.. with Maven `JAVA_HOME=/home/kubam/.jenv/versions/9-ea mvn jshell:compile -f maven/spark`
.. Other tooling support
... Netbeans
... IntelliJ

. Spark App exaple
.. import example.spark.*;
.. `Queue<Todo> store = new ConcurrentLinkedQueue<>()`
.. With memory storage +
+
[source]
----
App app = App.build().withPort(4567).withStorage(new InMemoryStorage(store)).build()
----

.. `app.run()`
.. `store.add(Todo.create(2, "Another todo", 2,true))`
.. Show in the web
.. add new on the web
.. `Todo.create(1, "Sample todo", 0, false)`
.. `store.add($6)`
.. show `store`

. Live reload
.. `import spark.*`
.. `import example.spark.*`
.. `Service ws = Service.ignite()`
.. `ws.port(35729)`
.. `ws.webSocket("/livereload", LiveReloadWebSocket.class);`
.. `ws.init()`
. Refresh the browser
.. `store.add(Todo.create(10, "Livereload Todo", 0, true))`
.. `LiveReloadWebSocket.broadcast()`

== Spring 5 example

. Maven Spring5 example
.. `JAVA_HOME=/home/kubam/.jenv/versions/9-ea mvn jshell:compile -f maven/spring5`
.. Basic classes +
+
[source]
----
public class Foo {
  	public final String text;

   	public Foo(String s) {
   		this.text = s;
   	}
}

public class Wrapper {
	public Wrapper(Foo foo) {
		System.out.println("Foo text from wrapper: " + foo.text);
	}
}
----

.. `import org.springframework.context.support.*`
.. `import org.springframework.context.annotation.*`
.. `GenericApplicationContext ctx = new AnnotationConfigApplicationContext()`
.. `ctx.registerBean(Foo.class, () -> new Foo("bar"))`
.. `ctx.registerBean(Wrapper.class, bd -> bd.setScope("prototype"))` //bean descriptor
.. `ctx.refresh()`
.. `ctx.getBean(Foo.class)`
.. `ctx.getBean(Wrapper.class)`

== Bonus - attributes

. You would normally run `java foo.Bar some arguments`
.. But if you try it with jshell - doesn't work
. So maybe system property
.. `java -Dname=value`
.. `jshell -Dfoo=bar`
. jshell style is environment variables
.. `export EDITOR=/usr/bin/vim`
.. jshell uses _vim_ as default
.. we can do it with other variables
