== Start of demo

[source]
start with: tmux attach || tmux new

== Environment and jshell

. jenv: `jenv shell 9-ea`
.. jenv not to mess with JDK version between different environments
.. like rvm but for Java
.. recently JDK is also featured package for sdkman.io

. running jshell for the first time
.. /help (/?)
.. `4+4`
.. `$5 + 4`
.. Variable naming
.. Using variables
.. Default imports (`Math.min()`)
.. Tab completion + Shift + Tab smart autocompletions

. commands
.. define interface +
+
[source]
----
interface ConvertToString {
	String apply(Integer i);
}
----
.. inline +
+
[source]
----
jshell> String convertToString(Integer i) {
   ...> return i.toString();
   ...> }
----
.. /edit toString
.. /set editor vim
.. /edit toString
.. /list
.. /vars
.. export EDITOR=/usr/bin/vim
.. /save `tofile`

== A canceled doctor's appointment

. Can we use JShell for something useful. A friend got doctors appointment rescheduled by 44 days. JShell can handle it
.. `import java.time.*`
.. `LocalDate.now().plusDays(44)`

== Java 9

=== Factory methods

. `Set.of()` - JAX-RS
.. `<Set<Class<?>> getClasses()` +
+
[source]
----
jshell> interface Application {
   ...> Set<Class<?>> getClasses();
   ...> }
----
.. `Application a = () -> new HashSet<Class<?>>(Arrays.asList(Math.class, Integer.class));`
.. `Application b = () -> Set.of(Math.class, Integer.class);`
. `List.of()`

=== Streams Enhancements

. `List<Integer> list = Arrays.asList(1, 2, 3, 4, null)`
. Map +
+
[source]
----
$1.stream()
	.map(Optional::ofNullable)
----
. No flatMap of Optional +
+
[source]
----
$1.stream()
  .map(Optional::ofNullable)
  .flatMap(o -> o.map(Stream::of).orElse(Stream.empty()))
  .forEach(System.out::println)
----
. `Optional::stream` +
+
[source]
----
$1.stream()
	.map(Optional::ofNullable)
	.flatMap(Optional::stream)
	.forEach(System.out::println)
----
. `takeWhile` +
+
[source]
----
$8.stream()
	.takeWhile(Objects::nonNull)
	.forEach(System.out::println)
----
. Infinite streams
+
[source]
----
IntStream.iterate(0, i -> 2 * i)
    .takeWhile(i -> i < 42)
    .forEach(System.out::println)
----
. Without `takeWhile` +
+
[source]
----
IntStream
	.iterate(1, i -> i < 42,  i -> i + 1)
	.forEach(System.out::println)
----

=== Http Client - prequel

. There will be a JDK HttpClient, but before we get there - how can we get data from URL
.. `InputStream is = new URL("http://ip.jsontest.com/").openStream()`
.. `InputStream.transferTo()`
... `ByteArrayOutputStream baos = new ByteArrayOutputStream()`
... `is.transferTo(baos)`

=== Http Client

. `/reset`
. http://download.java.net/java/jdk9/docs/api/jdk/incubator/http/HttpRequest.html
. jshell> /env --add-modules jdk.incubator.httpclient
. jshell> import jdk.incubator.http.*
. jshell> import jdk.incubator.http.HttpRequest.*
. jshell> import jdk.incubator.http.HttpResponse.*
.. The API will be included in JDK 9 as an incubating feature
.. Maybe JDK10 (I mean Java 18.3)
. Parse JSON from external URI (`http://ip.jsontest.com`)
.. Show it in console, curl
. URI uri = URI.create("http://ip.jsontest.com/");
. `HttpRequest.Builder` +
+
[source]
----
HttpRequest req = HttpRequest
	.newBuilder(uri)
	.GET()
	.build()
----
. `HttpClient.Buidler` +
+
[source]
----
HttpClient
	.newHttpClient()
	.send(req, BodyHandler.asString())
----
.. `sendAsyc()` works as well - out of the box
. headers in requests +
+
[source]
----
HttpRequest req = HttpRequest
	.newBuilder(uri)
	.header("Accept", "application/json")
	.GET()
	.build()
----

. Additional remarks
.. No - there are no specific plans to unify it with JAX-RS
.. It's based on Flow API (`HttpRequest.BodyProcessor` implements `Flow.Producer` while `HttpResponse.BodyProcessor` implements `Flow.Subscriber`
.. Gson path: /home/kubam/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar

== Working with external dependencies

. Starting with external deps
.. `/reset`
.. `/env --class-path /home/kubam/.m2/repository/com/sparkjava/spark-core/2.5/spark-core-2.5.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-api/1.7.24/slf4j-api-1.7.24.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-simple/1.7.24/slf4j-simple-1.7.24.jar:/home/kubam/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/home/kubam/.m2/repository/org/eclipse/jetty/aggregate/jetty-all/9.3.6.v20151106/jetty-all-9.3.6.v20151106-uber.jar:/home/kubam/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar`
.. `System.getProperty("java.class.path")`

. Initialize (`snippers/1_ignite.jsh`)
.. import spark.*
.. Service http = Service.ignite()
.. http.port(8888)
.. http.init()

. Basic endpoint
.. `Route r = (req, resp) -> ""`
.. /edit r
.. `route` +
+
[source]
----
Route r = (req, resp) -> {
	resp.header("Content-type", "application/json");
	return Map.of("foo", "bar");
}
----
== GSON

.. import com.google.gson.*
.. `Gson gson = new Gson()`
.. `http.get("/json", r, gson::toJson)`
.. show in the browser http://localhost:8888/json
.. `/save /tmp/json.jsh`
.. exit and load
... doesn't work - so start with `--class-path`
... `/home/kubam/.m2/repository/com/sparkjava/spark-core/2.5/spark-core-2.5.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-api/1.7.24/slf4j-api-1.7.24.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-simple/1.7.24/slf4j-simple-1.7.24.jar:/home/kubam/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/home/kubam/.m2/repository/org/eclipse/jetty/aggregate/jetty-all/9.3.6.v20151106/jetty-all-9.3.6.v20151106-uber.jar:/home/kubam/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar`
... doesn't work - so add `/env` command
... `/env --class-path /home/kubam/.m2/repository/com/sparkjava/spark-core/2.5/spark-core-2.5.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-api/1.7.24/slf4j-api-1.7.24.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-simple/1.7.24/slf4j-simple-1.7.24.jar:/home/kubam/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/home/kubam/.m2/repository/org/eclipse/jetty/aggregate/jetty-all/9.3.6.v20151106/jetty-all-9.3.6.v20151106-uber.jar:/home/kubam/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar`

== Application

. Show `snippets/JavaApp.class`
.. `export CP=/home/kubam/.m2/repository/com/sparkjava/spark-core/2.5/spark-core-2.5.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-api/1.7.24/slf4j-api-1.7.24.jar:/home/kubam/.m2/repository/org/slf4j/slf4j-simple/1.7.24/slf4j-simple-1.7.24.jar:/home/kubam/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/home/kubam/.m2/repository/org/eclipse/jetty/aggregate/jetty-all/9.3.6.v20151106/jetty-all-9.3.6.v20151106-uber.jar:/home/kubam/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar`
.. `javac -cp $CP snippets/JavaApp.java`
.. when compiles run it `java -cp .:$CP JavaApp`

== Application - endpoints

. If we can prepare snippets and run them, maybe we can prepare complete application
. Copy `JavaApp.java` to `app.jsh`
.. run it with `jshell --class-path $CP app.jsh`
.. backup: `/open snippets/2_application.jsh`
. show in browser
. add a simple Todo
. show in jshell
. `storage.clear()`
. show in browser

== Run from shell

. Run from bash `jshell snippets/2_application.jsh`
. Copy `snippets/2_application.jsh` to `bash_app.jsh`
. Add `&hash;!/opt/java/jdk-9/bin/jshell`
. `chmod a+x bash_app.jsh`
. Run it as a bash

== Mavenized project

. Maven
.. from jshell `jshell -c target/classes/:$CP`
.. with Maven `JAVA_HOME=/home/kubam/.jenv/versions/9-ea mvn jshell:compile -f maven/spark`
.. Other tooling support
... Netbeans
... IntelliJ

. Spark App exaple
.. import example.spark.*;
.. `Queue<Todo> store = new ConcurrentLinkedQueue<>()`
.. With memory storage +
+
[source]
----
App app = App.build().withPort(4567).withStorage(new InMemoryStorage(store)).build()
----

.. `app.run()`
.. `store.add(Todo.create(2, "Another todo", 2,true))`
.. Show in the web
.. add new on the web
.. `Todo.create(1, "Sample todo", 0, false)`
.. `store.add($6)`
.. show `store`

. Live reload
.. `import spark.*`
.. `import example.spark.*`
.. `Service ws = Service.ignite()`
.. `ws.port(35729)`
.. `ws.webSocket("/livereload", LiveReloadWebSocket.class);`
.. `ws.init()`
. Refresh the browser
.. `store.add(Todo.create(10, "Livereload Todo", 0, true))`
.. `LiveReloadWebSocket.broadcast()`

== Spring 5 example

. Maven Spring5 example
.. `JAVA_HOME=/home/kubam/.jenv/versions/9-ea mvn jshell:compile -f maven/spring5`
.. Basic classes +
+
[source]
----
public class Foo {
  	public final String text;

   	public Foo(String s) {
   		this.text = s;
   	}
}

public class Wrapper {
	public Wrapper(Foo foo) {
		System.out.println("Foo text from wrapper: " + foo.text);
	}
}
----

.. `import org.springframework.context.support.*`
.. `import org.springframework.context.annotation.*`
.. `GenericApplicationContext ctx = new AnnotationConfigApplicationContext()`
.. `ctx.registerBean(Foo.class, () -> new Foo("bar"))`
.. `ctx.registerBean(Wrapper.class, bd -> bd.setScope("prototype"))` //bean descriptor
.. `ctx.refresh()`
.. `ctx.getBean(Foo.class)`
.. `ctx.getBean(Wrapper.class)`

== Bonus - attributes

. You would normally run `java foo.Bar some arguments`
.. But if you try it with jshell - doesn't work
. So maybe system property
.. `java -Dname=value`
.. `jshell -Dfoo=bar`
. jshell style is environment variables
.. `export EDITOR=/usr/bin/vim`
.. jshell uses _vim_ as default
.. we can do it with other variables
... Even it sounds stupid, it seems coherent. That's the way you setup the editor so why not so the same with arguments
